import { ElementType } from '@/lib/types'

export const systemComponents: Array<{ type: ElementType; label: string; icon: string; description?: string }> = [
  { type: 'container', label: '容器', icon: '📦', description: '用于包裹其他组件的容器' },
  { type: 'layout', label: '布局', icon: '📐', description: '布局容器，包含两个子容器，允许添加模块' },
  { type: 'text', label: '文本', icon: '📝', description: '普通文本元素' },
  { type: 'button', label: '按钮', icon: '🔘', description: '可点击的按钮' },
  { type: 'input', label: '输入框', icon: '📥', description: '文本输入框' },
  { type: 'image', label: '图片', icon: '🖼️', description: '图片元素' },
  { type: 'card', label: '卡片', icon: '🎴', description: '卡片容器' },
  { type: 'heading', label: '标题', icon: '📌', description: '标题文本（H1-H6）' },
  { type: 'paragraph', label: '段落', icon: '📄', description: '段落文本' },
  { type: 'divider', label: '分割线', icon: '➖', description: '水平分割线' },
  { type: 'list', label: '列表', icon: '📋', description: '有序或无序列表' },
  { type: 'form', label: '表单', icon: '📋', description: '表单容器' },
]

export const antdComponents: Array<{ type: ElementType; label: string; icon: string; description?: string }> = [
  { type: 'a-button', label: 'Button', icon: '🔘', description: 'Ant Design 按钮' },
  { type: 'a-input', label: 'Input', icon: '📥', description: 'Ant Design 输入框' },
  { type: 'a-card', label: 'Card', icon: '🎴', description: 'Ant Design 卡片' },
  { type: 'a-form', label: 'Form', icon: '📋', description: 'Ant Design 表单' },
  { type: 'a-table', label: 'Table', icon: '📊', description: 'Ant Design 表格' },
  { type: 'a-select', label: 'Select', icon: '📋', description: 'Ant Design 选择器' },
  { type: 'a-datepicker', label: 'DatePicker', icon: '📅', description: 'Ant Design 日期选择器' },
  { type: 'a-radio', label: 'Radio', icon: '🔘', description: 'Ant Design 单选框' },
  { type: 'a-checkbox', label: 'Checkbox', icon: '☑️', description: 'Ant Design 复选框' },
  { type: 'a-switch', label: 'Switch', icon: '🔀', description: 'Ant Design 开关' },
  { type: 'a-slider', label: 'Slider', icon: '🎚️', description: 'Ant Design 滑动输入条' },
  { type: 'a-rate', label: 'Rate', icon: '⭐', description: 'Ant Design 评分' },
  { type: 'a-tag', label: 'Tag', icon: '🏷️', description: 'Ant Design 标签' },
  { type: 'a-badge', label: 'Badge', icon: '🔖', description: 'Ant Design 徽标数' },
  { type: 'a-avatar', label: 'Avatar', icon: '👤', description: 'Ant Design 头像' },
  { type: 'a-divider', label: 'Divider', icon: '➖', description: 'Ant Design 分割线' },
  { type: 'a-space', label: 'Space', icon: '↔️', description: 'Ant Design 间距' },
  { type: 'a-row', label: 'Row', icon: '➡️', description: 'Ant Design 行' },
  { type: 'a-col', label: 'Col', icon: '⬇️', description: 'Ant Design 列' },
  { type: 'a-layout', label: 'Layout', icon: '📐', description: 'Ant Design 布局' },
  { type: 'a-menu', label: 'Menu', icon: '📑', description: 'Ant Design 导航菜单' },
  { type: 'a-tabs', label: 'Tabs', icon: '📑', description: 'Ant Design 标签页' },
  { type: 'a-collapse', label: 'Collapse', icon: '📂', description: 'Ant Design 折叠面板' },
  { type: 'a-timeline', label: 'Timeline', icon: '⏱️', description: 'Ant Design 时间轴' },
  { type: 'a-list', label: 'List', icon: '📋', description: 'Ant Design 列表' },
  { type: 'a-empty', label: 'Empty', icon: '📭', description: 'Ant Design 空状态' },
  { type: 'a-spin', label: 'Spin', icon: '🌀', description: 'Ant Design 加载中' },
  { type: 'a-alert', label: 'Alert', icon: '⚠️', description: 'Ant Design 警告提示' },
  { type: 'a-popover', label: 'Popover', icon: '💭', description: 'Ant Design 气泡卡片' },
]

export const getDefaultProps = (type: ElementType): Record<string, any> => {
  const defaults: Record<string, Record<string, any>> = {
    container: {},
    layout: {},
    text: { text: '文本' },
    button: { text: '按钮', variant: 'primary' },
    input: { placeholder: '请输入' },
    image: { src: '', alt: '图片' },
    card: {},
    divider: {},
    heading: { text: '标题', level: 1 },
    paragraph: { text: '段落文本' },
    list: { items: ['项目1', '项目2'], ordered: false },
    form: {
      fields: [],
      labelWidth: 122,
      labelWrap: true,
      labelEllipsis: false,
      layout: 'horizontal',
      rowGap: 16,
      submitLabel: '提交',
      cancelLabel: '取消',
    },
    'a-button': { text: 'Button', type: 'default' },
    'a-input': { placeholder: '请输入' },
    'a-card': { title: 'Card Title' },
    'a-form': {},
    'a-select': { placeholder: '请选择' },
    'a-datepicker': {},
    'a-radio': { label: 'Radio' },
    'a-checkbox': { label: 'Checkbox' },
    'a-switch': {},
    'a-slider': {},
    'a-rate': {},
    'a-tag': { text: 'Tag' },
    'a-badge': { count: 0 },
    'a-avatar': {},
    'a-divider': {},
    'a-space': {},
    'a-row': {},
    'a-col': { span: 12 },
    'a-layout': {},
    'a-menu': {},
    'a-tabs': {
      items: [
        { key: 'tab-1', label: '标签页 1', children: [] },
        { key: 'tab-2', label: '标签页 2', children: [] },
      ],
    },
    'a-collapse': {},
    'a-timeline': {},
    'a-list': {},
    'a-empty': {},
    'a-spin': {},
    'a-alert': { message: 'Alert', type: 'info' },
    'a-popover': { title: 'Popover标题', content: 'Popover内容' },
  }
  return defaults[type] || {}
}
