import {
  SearchOutlined,
  EditOutlined,
  DeleteOutlined,
  SaveOutlined,
  DownloadOutlined,
  UploadOutlined,
  PlusOutlined,
  MinusOutlined,
  CheckOutlined,
  CloseOutlined,
  UserOutlined,
  UserAddOutlined,
  TeamOutlined,
  SettingOutlined,
  LogoutOutlined,
  HomeOutlined,
  MenuOutlined,
  ArrowLeftOutlined,
  ArrowRightOutlined,
  ArrowUpOutlined,
  ArrowDownOutlined,
  FileOutlined,
  FolderOutlined,
  FileAddOutlined,
  FileTextOutlined,
  PictureOutlined,
  MailOutlined,
  MessageOutlined,
  PhoneOutlined,
  NotificationOutlined,
  HeartOutlined,
  StarOutlined,
  LikeOutlined,
  ShareAltOutlined,
  ReloadOutlined,
  SyncOutlined,
  LoadingOutlined,
  InfoCircleOutlined,
  QuestionCircleOutlined,
  WarningOutlined,
} from '@ant-design/icons'
import React from 'react'

// 图标映射表
export const iconMap: Record<string, React.ComponentType<any>> = {
  SearchOutlined,
  EditOutlined,
  DeleteOutlined,
  SaveOutlined,
  DownloadOutlined,
  UploadOutlined,
  PlusOutlined,
  MinusOutlined,
  CheckOutlined,
  CloseOutlined,
  UserOutlined,
  UserAddOutlined,
  TeamOutlined,
  SettingOutlined,
  LogoutOutlined,
  HomeOutlined,
  MenuOutlined,
  ArrowLeftOutlined,
  ArrowRightOutlined,
  ArrowUpOutlined,
  ArrowDownOutlined,
  FileOutlined,
  FolderOutlined,
  FileAddOutlined,
  FileTextOutlined,
  PictureOutlined,
  MailOutlined,
  MessageOutlined,
  PhoneOutlined,
  NotificationOutlined,
  HeartOutlined,
  StarOutlined,
  LikeOutlined,
  ShareAltOutlined,
  ReloadOutlined,
  SyncOutlined,
  LoadingOutlined,
  InfoCircleOutlined,
  QuestionCircleOutlined,
  WarningOutlined,
}

// 图标选项配置
export const iconOptions = [
  { value: '', label: '无图标', group: '' },
  { value: 'SearchOutlined', label: '搜索', group: '常用操作', icon: SearchOutlined },
  { value: 'EditOutlined', label: '编辑', group: '常用操作', icon: EditOutlined },
  { value: 'DeleteOutlined', label: '删除', group: '常用操作', icon: DeleteOutlined },
  { value: 'SaveOutlined', label: '保存', group: '常用操作', icon: SaveOutlined },
  { value: 'DownloadOutlined', label: '下载', group: '常用操作', icon: DownloadOutlined },
  { value: 'UploadOutlined', label: '上传', group: '常用操作', icon: UploadOutlined },
  { value: 'PlusOutlined', label: '添加', group: '常用操作', icon: PlusOutlined },
  { value: 'MinusOutlined', label: '减少', group: '常用操作', icon: MinusOutlined },
  { value: 'CheckOutlined', label: '确认', group: '常用操作', icon: CheckOutlined },
  { value: 'CloseOutlined', label: '关闭', group: '常用操作', icon: CloseOutlined },
  { value: 'UserOutlined', label: '用户', group: '用户相关', icon: UserOutlined },
  { value: 'UserAddOutlined', label: '添加用户', group: '用户相关', icon: UserAddOutlined },
  { value: 'TeamOutlined', label: '团队', group: '用户相关', icon: TeamOutlined },
  { value: 'SettingOutlined', label: '设置', group: '用户相关', icon: SettingOutlined },
  { value: 'LogoutOutlined', label: '退出', group: '用户相关', icon: LogoutOutlined },
  { value: 'HomeOutlined', label: '首页', group: '导航', icon: HomeOutlined },
  { value: 'MenuOutlined', label: '菜单', group: '导航', icon: MenuOutlined },
  { value: 'ArrowLeftOutlined', label: '左箭头', group: '导航', icon: ArrowLeftOutlined },
  { value: 'ArrowRightOutlined', label: '右箭头', group: '导航', icon: ArrowRightOutlined },
  { value: 'ArrowUpOutlined', label: '上箭头', group: '导航', icon: ArrowUpOutlined },
  { value: 'ArrowDownOutlined', label: '下箭头', group: '导航', icon: ArrowDownOutlined },
  { value: 'FileOutlined', label: '文件', group: '文件', icon: FileOutlined },
  { value: 'FolderOutlined', label: '文件夹', group: '文件', icon: FolderOutlined },
  { value: 'FileAddOutlined', label: '添加文件', group: '文件', icon: FileAddOutlined },
  { value: 'FileTextOutlined', label: '文本文件', group: '文件', icon: FileTextOutlined },
  { value: 'PictureOutlined', label: '图片', group: '文件', icon: PictureOutlined },
  { value: 'MailOutlined', label: '邮件', group: '通信', icon: MailOutlined },
  { value: 'MessageOutlined', label: '消息', group: '通信', icon: MessageOutlined },
  { value: 'PhoneOutlined', label: '电话', group: '通信', icon: PhoneOutlined },
  { value: 'NotificationOutlined', label: '通知', group: '通信', icon: NotificationOutlined },
  { value: 'HeartOutlined', label: '收藏', group: '其他', icon: HeartOutlined },
  { value: 'StarOutlined', label: '星标', group: '其他', icon: StarOutlined },
  { value: 'LikeOutlined', label: '点赞', group: '其他', icon: LikeOutlined },
  { value: 'ShareAltOutlined', label: '分享', group: '其他', icon: ShareAltOutlined },
  { value: 'ReloadOutlined', label: '刷新', group: '其他', icon: ReloadOutlined },
  { value: 'SyncOutlined', label: '同步', group: '其他', icon: SyncOutlined },
  { value: 'LoadingOutlined', label: '加载中', group: '其他', icon: LoadingOutlined },
  { value: 'InfoCircleOutlined', label: '信息', group: '其他', icon: InfoCircleOutlined },
  { value: 'QuestionCircleOutlined', label: '帮助', group: '其他', icon: QuestionCircleOutlined },
  { value: 'WarningOutlined', label: '警告', group: '其他', icon: WarningOutlined },
]

