import { Element, ElementType } from '../types'

// Vue 2 代码生成器
export class VueGenerator {
  private indent = 0
  private indentSize = 2

  private indentStr(): string {
    return ' '.repeat(this.indent * this.indentSize)
  }

  private formatStyle(style?: Record<string, string | number>): string {
    if (!style || Object.keys(style).length === 0) {
      return ''
    }
    const styleEntries = Object.entries(style).map(([key, value]) => {
      const cssKey = key.replace(/([A-Z])/g, '-$1').toLowerCase()
      return `${cssKey}: ${typeof value === 'number' ? `${value}px` : value}`
    })
    return ` style="${styleEntries.join('; ')}"`
  }

  /**
   * 生成组件类名（用于代码搜索定位）
   * 格式：pb-{type}，例如：pb-button, pb-container
   */
  private getComponentClassName(type: ElementType): string {
    return `pb-${type}`
  }

  /**
   * 合并类名（组件类名 + 用户自定义类名）
   */
  private mergeClassNames(componentClass: string, userClassName?: string): string {
    const classes = [componentClass]
    if (userClassName) {
      classes.push(userClassName)
    }
    return classes.join(' ')
  }

  private formatProps(props: Record<string, any>, excludeClassName: boolean = true): string {
    const propEntries = Object.entries(props)
      .filter(([key, value]) => {
        // 排除 className，因为它已经在 classNameStr 中处理了
        if (excludeClassName && key === 'className') {
          return false
        }
        return value !== undefined && value !== null && value !== ''
      })
      .map(([key, value]) => {
        if (typeof value === 'boolean') {
          return value ? key : ''
        }
        if (typeof value === 'string') {
          return `${key}="${value}"`
        }
        return `:${key}="${JSON.stringify(value)}"`
      })
      .filter(Boolean)
    return propEntries.length > 0 ? ' ' + propEntries.join(' ') : ''
  }

  private generateElementCode(element: Element): string {
    const { type, props, style, className, children } = element
    const styleStr = this.formatStyle(style)
    
    // 生成组件类名（pb-{type}）并合并用户自定义类名
    // 每个组件都有 pb-{type} 类名，方便代码搜索定位
    const componentClass = this.getComponentClassName(type)
    const mergedClassName = this.mergeClassNames(componentClass, className)
    const classNameStr = ` class="${mergedClassName}"`
    
    const propsStr = this.formatProps(props || {}, true)

    let tag = this.getElementTag(type, props || {})
    let isSelfClosing = this.isSelfClosingTag(tag)

    // 如果有子元素或文本内容，不是自闭合标签
    if (children && children.length > 0) {
      isSelfClosing = false
    }
    if ((props && props.text) || (props && props.content)) {
      isSelfClosing = false
    }

    if (isSelfClosing) {
      return `${this.indentStr()}<${tag}${propsStr}${classNameStr}${styleStr} />`
    }

    const openTag = `${this.indentStr()}<${tag}${propsStr}${classNameStr}${styleStr}>`
    const closeTag = `${this.indentStr()}</${tag}>`

    let content = ''

    // 处理文本内容
    if (props && props.text) {
      content += `\n${this.indentStr()}  ${props.text}`
    } else if (props && props.content) {
      content += `\n${this.indentStr()}  ${props.content}`
    }

    // 处理子元素
    if (children && children.length > 0) {
      this.indent++
      for (const child of children) {
        content += '\n' + this.generateElementCode(child)
      }
      this.indent--
    }

    if (content) {
      return `${openTag}${content}\n${closeTag}`
    }

    return `${openTag}${closeTag}`
  }

  private getElementTag(type: ElementType, props: Record<string, any>): string {
    const tagMap: Record<ElementType, string> = {
      container: 'div',
      text: 'span',
      button: 'button',
      input: 'input',
      image: 'img',
      card: 'div',
      divider: 'hr',
      heading: 'h1',
      paragraph: 'p',
      list: 'ul',
      form: 'form',
    }

    // 根据 type 和 props 决定具体标签
    if (type === 'heading') {
      return props?.level ? `h${props.level}` : 'h1'
    }
    if (type === 'list') {
      return props?.ordered ? 'ol' : 'ul'
    }

    return tagMap[type] || 'div'
  }

  private isSelfClosingTag(tag: string): boolean {
    const selfClosingTags = ['input', 'img', 'hr', 'br']
    return selfClosingTags.includes(tag.toLowerCase())
  }

  generate(element: Element, componentName: string = 'GeneratedPage'): string {
    this.indent = 0

    const template = this.generateElementCode(element)
    const script = `<script>
export default {
  name: '${componentName}',
  // Auto-generated by Page Builder
  // Each element has a pb-{type} class name for easy searching and locating in code
}
</script>`

    const style = `<style scoped>
/* Auto-generated styles */
/* Component class names follow the pattern: pb-{type} (e.g., pb-button, pb-container) */
</style>`

    return `<template>
${template}
</template>

${script}

${style}
`.trim()
  }

  generateFromConfig(elements: Element[], componentName: string = 'GeneratedPage'): string {
    // 如果只有一个根元素，直接生成
    if (elements.length === 1) {
      return this.generate(elements[0], componentName)
    }

    // 多个根元素，包裹在一个容器中
    const container: Element = {
      id: 'root-container',
      type: 'container',
      props: {},
      children: elements,
    }

    return this.generate(container, componentName)
  }
}
